DROP TABLE IF EXISTS Bids;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Items; 
DROP TABLE IF EXISTS Users;

CREATE TABLE Users 
(userId VARCHAR PRIMARY KEY,
rating REAL NOT NULL,
country VARCHAR,
location VARCHAR);

CREATE TABLE Items 
(itemId INTEGER PRIMARY KEY,
name VARCHAR NOT NULL,
seller VARCHAR NOT NULL,
description TEXT,
currently REAL NOT NULL,
firstBid REAL NOT NULL,
buyPrice REAL,
numberBids INTEGER NOT NULL,
started DATE NOT NULL,
ends DATE NOT NULL CHECK (ends >  started),
FOREIGN KEY (seller) REFERENCES Users (userId) ON UPDATE CASCADE);

CREATE TABLE Categories 
(itemId INTEGER,
category VARCHAR NOT NULL, 
PRIMARY KEY(itemId, category),
FOREIGN KEY (itemId) REFERENCES Items(itemId) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE Bids 
(itemId INTEGER,
userId VARCHAR,
time DATE NOT NULL,
amount REAL NOT NULL,
PRIMARY KEY (itemId, userId, amount),
FOREIGN KEY (itemId) REFERENCES Items(itemId) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE ON UPDATE CASCADE);


